// <auto-generated />
using System;
using Kimbito.Infra.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace webapi.Migrations
{
    [DbContext(typeof(KimbitoDbContext))]
    [Migration("20260219100000_AddEcommerceAndNivel")]
    partial class AddEcommerceAndNivel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Snapshot is in KimbitoDbContextModelSnapshot - same model after this migration
        }
    }
}
