FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["webapi.csproj", "./"]
RUN dotnet restore "webapi.csproj"

COPY . .
RUN dotnet publish "webapi.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app 

COPY --from=build /app/publish .

EXPOSE 5248

ENTRYPOINT ["dotnet", "webapi.dll"]
